2024-12-24 14:44:16,714 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\Установка виртуального окружения\module_11_virt_environments\tests_12_4.py", line 21, in test_run
    begun = Runner(31331)
            ^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\Установка виртуального окружения\module_11_virt_environments\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-24 14:44:16,717 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\Установка виртуального окружения\module_11_virt_environments\tests_12_4.py", line 11, in test_walk
    peshehod = Runner('Пешеход', -3)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\Установка виртуального окружения\module_11_virt_environments\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
